font_family      FiraCode Nerd Font
font_size 12.0
cursor #c7c7c7
cursor_text_color #FEFFFF
scrollback_lines 10000
enabled_layouts fat
window_padding_width 5
confirm_os_window_close 1
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style angled
tab_title_template " {index}: {'{: <501}'.format(title)}"
foreground #D1D2D3
background #16171E
background_opacity 0.95
background_tint 0.1
color0 #000000
color8 #676767
color1 #E68E8E
color9 #FF6D67
color2  #83AC8E
color10 #5FF967
color3  #F5B78A
color11 #FEFB67
color4  #9BB8DC
color12 #6871FF
color5  #BAACE2
color13 #FF76FF
color6  #00C5C7
color14 #5FFDFF
color7  #C7C7C7
color15 #FEFFFF
shell /bin/zsh
allow_remote_control yes
listen_on unix:/tmp/kitty
