[tools]
bat = "latest"
jq = "latest"
lsd = "latest"
zoxide = "latest"
starship = "latest"
neovim = "latest"
go = "latest"
fzf = "latest"
python = "latest"
yt-dlp = "latest"
gh = "latest"
ghq = "latest"
pnpm = "latest"
chezmoi = "latest"
duckdb = "latest"
deno = "latest"
actionlint = "latest"
difftastic = "latest"
awscli = "latest"
ghalint = "latest"
lefthook = "latest"
hadolint = "latest"
task = "latest"
ripgrep = "latest"
terraform = "latest"
ffmpeg = "latest"
